// 03.Angular-2/Angular2-Exam-13-08-2017/client/src/app/core/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, NavigationStart } from '@angular/router';
import { AuthService } from './auth.service';

@Component({
  selector: 'navbar',
  templateUrl: './navbar.component.html'
})

export class NavbarComponent implements OnInit {
  authenticated: boolean = false;
  username: string = null;
  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit() {
     this.router.events.subscribe(ev => {
      if(ev instanceof NavigationStart) {
          this.authenticated = this.authService.isUserAuthenticated();
          this.username = this.authService.getUser();
      }
    });
  }
  logout() {
    this.authenticated = false;
    this.authService.deauthenticateUser();
    this.authService.removeUser();
    this.router.navigateByUrl('');
  }
}
<div>
  <span>
     <a routerLink="/">Home</a> 
     <a routerLink="animals/all">All Animals</a>
  </span>
  <span *ngIf="authenticated"> 
     <a routerLink="animals/add">Add Animal</a>
     <a routerLink="users/profile">{{username}}</a>
     <a href="javascript:void(0);" (click)="logout()">Logout</a> 
  </span>
  <span *ngIf="!authenticated"> 
    <a routerLink="/users/register">Register</a>
    <a routerLink="/users/login">Login</a>
  </span>
</div>

// 02.ReactJS/Reactjs-Exam-16-07-2017/carSystemReact/src/components/common/Navbar.js
import React from 'react'
import { Link } from 'react-router-dom'
import Auth from '../users/Auth'
import userStore from '../../stores/UserStore'
class Navbar extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      username: Auth.getUser().name
    }
    this.handleUserLoggedIn = this.handleUserLoggedIn.bind(this)
    userStore.on(userStore.eventTypes.USER_LOGGED_IN,
    this.handleUserLoggedIn)
  }
  handleUserLoggedIn (data) {
    if (data.success) {
      this.setState({
        username: data.user.name
      })
    }
  }
  render () {
    return (
      <div className='menu'>
        {Auth.isUserAuthenticated() ? (
          <div>
            <Link to='/'>Home</Link>
            <Link to='/cars/all'>All Cars</Link>
            <Link to='/cars/create'>Add</Link>
            <span>{this.state.username}</span>
            <Link to='/cars/mine'>Profile</Link>
            <Link to='/users/logout'>Logout</Link>
          </div>
    ) : (
      <div>
        <Link to='/'>Home</Link>
        <Link to='/cars/all'>All Cars</Link>
        <Link to='/users/register'>Register</Link>
        <Link to='/users/login'>Login</Link>
      </div>
    )}
      </div>
    )
  }
}

export default Navbar
